// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.30.2
// source: proto/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

export interface FindAllUsersResponse {
  data: Users | undefined;
  total: number;
  page: number;
  limit: number;
}

export interface Message {
  message: string;
}

/** Empty message */
export interface Empty {
}

export interface Users {
  users: User[];
}

export interface UserId {
  id: string;
}

export interface FindOneUserByEmailDto {
  email: string;
}

export interface UpdateUserDto {
  id: string;
  address?: string | undefined;
  location?: string | undefined;
  socialMedia?: SocialMedia | undefined;
  gymId?: string | undefined;
  gymLocationId?: string | undefined;
  role?: string | undefined;
}

export interface CreateUserDto {
  lastName: string;
  firstName: string;
  dateOfBirth: string;
  email: string;
  location: string;
  address: string;
  provider: string;
  password?: string | undefined;
  gymId?: string | undefined;
  gymLocationId?: string | undefined;
  role: string;
}

export interface FindAllUsersDto {
  page: number;
  limit: number;
  offset: number;
  search?: string | undefined;
  filter?: FilterUsersDto | undefined;
}

export interface FilterUsersDto {
  location?: string | undefined;
  isActive?: boolean | undefined;
  isSubscribed?: boolean | undefined;
  isDeleted?: boolean | undefined;
  role?: string | undefined;
}

export interface User {
  id: string;
  lastName: string;
  firstName: string;
  dateOfBirth: string;
  email: string;
  location: string;
  address: string;
  provider: string;
  password?: string | undefined;
  role: string;
  isActive: boolean;
  isSubscribed: boolean;
  isDeleted: boolean;
  socialMedia?: SocialMedia | undefined;
  gymId: string;
  gymLocationId: string;
  createdAt: string;
  updatedAt: string;
}

export interface SocialMedia {
  facebookUsername?: string | undefined;
  twitterUri?: string | undefined;
  instagramUri?: string | undefined;
  tiktokUri?: string | undefined;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface UsersServiceClient {
  createUser(request: CreateUserDto): Observable<User>;

  findAllUsers(request: FindAllUsersDto): Observable<FindAllUsersResponse>;

  findOneUser(request: UserId): Observable<User>;

  findOneUserByEmail(request: FindOneUserByEmailDto): Observable<User>;

  updateUser(request: UpdateUserDto): Observable<User>;

  removeUser(request: UserId): Observable<Message>;
}

export interface UsersServiceController {
  createUser(request: CreateUserDto): Promise<User> | Observable<User> | User;

  findAllUsers(
    request: FindAllUsersDto,
  ): Promise<FindAllUsersResponse> | Observable<FindAllUsersResponse> | FindAllUsersResponse;

  findOneUser(request: UserId): Promise<User> | Observable<User> | User;

  findOneUserByEmail(request: FindOneUserByEmailDto): Promise<User> | Observable<User> | User;

  updateUser(request: UpdateUserDto): Promise<User> | Observable<User> | User;

  removeUser(request: UserId): Promise<Message> | Observable<Message> | Message;
}

export function UsersServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createUser",
      "findAllUsers",
      "findOneUser",
      "findOneUserByEmail",
      "updateUser",
      "removeUser",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USERS_SERVICE_NAME = "UsersService";
