// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.30.2
// source: proto/gyms.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "gyms";

export interface CreateGymDto {
  name: string;
  slug: string;
  config?: GymConfig | undefined;
}

export interface GymConfig {
  logoUrl?: string | undefined;
  email?: string | undefined;
  phoneNumber?: string | undefined;
  websiteUrl?: string | undefined;
  policies?: string | undefined;
}

export interface FindAllGymsDto {
  page: number;
  limit: number;
  offset: number;
  search?: string | undefined;
  filter?: FilterGymsDto | undefined;
}

export interface FilterGymsDto {
  name?: string | undefined;
}

export interface FindAllGymsResponse {
  data: Gyms | undefined;
  total: number;
  page: number;
  limit: number;
}

export interface Gyms {
  gyms: Gym[];
}

export interface Gym {
  id: string;
  name: string;
  slug: string;
  config: GymConfig | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface GymId {
  id: string;
}

export interface UpdateGymDto {
  id: string;
  name?: string | undefined;
  slug?: string | undefined;
  config?: GymConfig | undefined;
}

export interface RemoveGymDto {
  id: string;
}

export interface Message {
  message: string;
}

export const GYMS_PACKAGE_NAME = "gyms";

export interface GymsServiceClient {
  createGym(request: CreateGymDto): Observable<Gym>;

  findAllGyms(request: FindAllGymsDto): Observable<FindAllGymsResponse>;

  findOneGym(request: GymId): Observable<Gym>;

  updateGym(request: UpdateGymDto): Observable<Gym>;

  removeGym(request: RemoveGymDto): Observable<Message>;
}

export interface GymsServiceController {
  createGym(request: CreateGymDto): Promise<Gym> | Observable<Gym> | Gym;

  findAllGyms(
    request: FindAllGymsDto,
  ): Promise<FindAllGymsResponse> | Observable<FindAllGymsResponse> | FindAllGymsResponse;

  findOneGym(request: GymId): Promise<Gym> | Observable<Gym> | Gym;

  updateGym(request: UpdateGymDto): Promise<Gym> | Observable<Gym> | Gym;

  removeGym(request: RemoveGymDto): Promise<Message> | Observable<Message> | Message;
}

export function GymsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createGym", "findAllGyms", "findOneGym", "updateGym", "removeGym"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("GymsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("GymsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const GYMS_SERVICE_NAME = "GymsService";
